// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

#pragma once
#include <string>

namespace GameKit
{
    namespace Configuration
    {
        static const std::string DO_NOT_EDIT = "#\n# DO NOT MANUALLY EDIT\n#\n# Autogenerated by AWS GameKit\n#\n";
    }
}